abstract class TouristCitiesConstants {
  static const List<String> touristCities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Luxor",
    "Aswan",
    "Sharm El Sheikh",
    "Hurghada",
    "Dahab",
    "Marsa Alam",
    "El Gouna",
    "Taba",
    "Nuweiba",
    "Siwa",
    "Port Said",
    "Suez",
    "Ismailia",
    "Fayoum",
    "Minya",
    "Ain Sokhna",
    "Ras Sedr",
    "Safaga",
    "Quseir",
    "Abu Simbel",
    "New Alamein",
    "Matrouh",
  ];
}
